### ISSUE TITLE
Color Picker stays after "Cancel"

### ISSUE THREAD

**Issue by Pdzly** [pwillia7/Text_Bookmarklet#1]
# Expected Result

1. I edit the color of an item.
2. I cancel it in the popup
3. The popup closes and the color picker hides itself.

# Actual Result

1. I edit the color of an item.
2. I cancel it in the popup
3. The popup closes BUT the color picker stays and is stuck until reload.

# Specs:

Up to date Firefox 
Linux

![image](https://github.com/pwillia7/Text_Bookmarklet/assets/34943569/e560d63a-ac34-4c88-984e-2cabcb853cc6)

**Comment by pwillia7** [comment]
Can you let me know if this is still happening? The version in your screenshot is out of date and I believe this is fixed now.

**Comment by Pdzly** [comment]
Yeah will test in a sec!

**Comment by Pdzly** [comment]
@pwillia7 sadly its still up! I use linux, firefox if that helps to debug!

**Comment by pwillia7** [comment]
Fixed! TY for patience.
